### ISSUE TITLE
Update to Deno v1.25.0 & enable unstable APIs

### ISSUE THREAD

**Issue by BenjaminAster** [jespertheend/deno-types#1]
[Deno v1.25.0](https://deno.com/blog/v1.25) has just been released and includes the experimental `Deno.serve()` API. Would be awesome if you could `deno upgrade` your Deno to v1.25.0 and publish the changes to npm. Also, I think you should enable the unstable types by changing line 6 of `./generate.js` to include `"--unstable"` as the third array item of `cmd`.

Btw, thanks for making this repository, this is exactly what I was looking for! I was planning to create unofficial type declarations for Deno by myself, and just checked a few npm package names (including `deno-types`) if someone else already had this idea, and turns out, yes, they did! I hate to always enable the Deno VSCode extension just for a small Deno script without any external dependencies, so this what I often need.

**Comment by jespertheend** [comment]
Ah cool, didn't know anyone was using this. I'll try to update it later today.
In the mean time, you might want to take a look at https://deno.land/x/deno_tsc_helper@v0.0.12/mod.js which might better suit your needs as it uses your currently installed Deno version, though I haven't tested it with 1.25.0 yet.
I haven't had time to add much documentation yet but you can find an example at https://github.com/rendajs/Renda/blob/main/scripts/dev.js

**Comment by jespertheend** [comment]
Should be up at https://www.npmjs.com/package/deno-types now!
I don't think there's a convenient way to publish both the stable and unstable types without either publishing another package or creating two separate directories, so I've just enabled `--unstable` by default for now.
